language: node_js
node_js: 5
before_script:
- npm install -g gulp
script: gulp production
cache:
  directories:
    - ./node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: vy7V5ooO2yMVYQx9qsmvN3WSrljpf3aQoFpfdQkVjpFU8I65vm64PUSE07GfSXL+xjPkGqZa96YpLp0VmnRhykWwkBEc6p0WlS24KjusaIVFJRgEr3F+Sm2Kz7P7OjNedW1oXSclUuNwbxboYQYAnPRVvF7cLxtkdJGXr7GGt+qTJf8aKe6tMp3cItI01Rnoy0m2PqC1ZeGJM5/qVqzC7rvFjUcYNEjQjc7JOOQUDSOuPHCQ+vUOBGMG2b6s+vFUF4C74O3VBp2xrYGfy1xjRDAPl2jljLds7051+4uqaLVExx3C60s8ESSNMpEiMIiO2hxqxDqzUU5wZuE4p548c2uyRG1uhYpdG+sIbM2TAaL+LsLXVswMM0jBcBtxuIg73uIRkxD0x/RiVaT/4RIe6LZPjiThqbKvsN72N+atVYFZq4x9xpeA12j7PYwJ20e3JlLXxSJ6HswN8yZ/Mok4UHF//XHIY5lwPZv8fMX5ycq8u0mg/wWFl4WbZ/NA8CCTmD+TrKSTeCaAiu1JHVoyvYdhW/UwOSMZCXoyyYd5rQXt4uTQSFy0F1EFnRdEWHsocxJEUfQb158leox6RbBnY9z0cJcNDVp8pIb6PfJXIWeoX6/b6ZWS8VQoZrfJpTR2eM6DQ0ox5YgWMgI0cqZTM9OWjvWYEI+4egW/k3/4JJI=
  app: reflux-todo-app
  on:
    repo: arajparaj/reflux-todo
